baseURL = 'https://ka-iden.github.io/'
languageCode = 'en-us'
title = 'ka-iden'

# Disable Hugo's default date handling
# This ensures future dated posts always appear
ignoreFutureDate = false

[params]
  description = "Personal portfolio and blog of Kaiden"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

# Content building options
buildFuture = true  # Required for future-dated content to appear
buildExpired = true  # Include expired content
buildDrafts = true   # Include content marked as drafts

# URL management
[permalinks]
  blog = "/blog/:filename/"
  projects = "/projects/:filename/"

# Section configuration
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

# Ensure section pages are properly created
[taxonomies]
  category = "categories"
  tag = "tags"
